/*###############################################################
BDS function symbols and RVAs
File generated by BDumper, a rust bds pdb dumper made by Luke7720
###############################################################*/
#pragma once

//37037
//?getBlock@BlockSource@@QEBAAEBVBlock@@AEBVBlockPos@@@Z;
constexpr unsigned int b_OVEWoaoj = 0xf8b490;

//40344
//?getBlockEntity@BlockSource@@QEAAPEAVBlockActor@@AEBVBlockPos@@@Z;
constexpr unsigned int WcoDPEQrUn = 0xf8b5e0;

//41300
//?_checkAttachedBlocks@PistonBlockActor@@AEAA_NAEAVBlockSource@@@Z;
constexpr unsigned int fFEJoOUAfG = 0x10dc620;

//105578
//?getPos@Actor@@UEBAAEBVVec3@@XZ;
constexpr unsigned int eUAXxYCSqy = 0xba35c0;

//135660
//?getCorrectArmBlock@PistonBlockActor@@QEBAPEBVBlock@@XZ;
constexpr unsigned int tkCx_axzTD = 0x10e9aa0;

//209261
//?getNameTag@Actor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ;
constexpr unsigned int xyMjHVevKQ = 0xba3260;

//249200
//?getId@ItemStackBase@@QEBAFXZ;
constexpr unsigned int mgDiVqYgWO = 0xc86b90;

//275487
//?canSurvive@PistonBlock@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z;
constexpr unsigned int WfEASBMNQp = 0x1252cc0;

//279930
//?isExpanding@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int eDWwWumtrL = 0x10ebe40;

//324681
//?displayLocalizableMessage@CommandUtils@@YAX_NAEAVPlayer@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@@Z;
constexpr unsigned int MkBCBQogcO = 0x7826b0;

//337902
//?isRetracting@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int Xq_Bdi_TjC = 0x10ebe50;

//356766
//?isExpanded@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int D_LHvgIEZR = 0x10ebe20;

//486068
//?getName@ItemStackBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ;
constexpr unsigned int bFRmLvs_hd = 0xc87110;