/*###############################################################
BDS function symbols and RVAs
File generated by BDumper, a rust bds pdb dumper made by Luke7720
###############################################################*/
#pragma once

//?getBlock@BlockSource@@QEBAAEBVBlock@@AEBVBlockPos@@@Z;
constexpr unsigned int b_OVEWoaoj = 0xfaa0b0;

//?getBlockEntity@BlockSource@@QEAAPEAVBlockActor@@AEBVBlockPos@@@Z;
constexpr unsigned int WcoDPEQrUn = 0xfaa1b0;

//?_checkAttachedBlocks@PistonBlockActor@@AEAA_NAEAVBlockSource@@@Z;
constexpr unsigned int fFEJoOUAfG = 0x1258c00;

//?getPos@Actor@@UEBAAEBVVec3@@XZ;
constexpr unsigned int eUAXxYCSqy = 0xb41ff0;

//?getCorrectArmBlock@PistonBlockActor@@QEBAPEBVBlock@@XZ;
constexpr unsigned int tkCx_axzTD = 0x1260470;

//?getNameTag@Actor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ;
constexpr unsigned int xyMjHVevKQ = 0xb41ad0;

//?getId@ItemStackBase@@QEBAFXZ;
constexpr unsigned int mgDiVqYgWO = 0xc8c120;

//?_attachedBlockWalker@PistonBlockActor@@AEAA_NAEAVBlockSource@@AEBVBlockPos@@EE@Z;
constexpr unsigned int DRHTpLpIcu = 0x12580a0;

//?canSurvive@PistonBlock@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z;
constexpr unsigned int WfEASBMNQp = 0x1277c20;

//?isExpanding@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int eDWwWumtrL = 0x1260fa0;

//?displayLocalizableMessage@CommandUtils@@YAX_NAEAVPlayer@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@@Z;
//constexpr unsigned int MkBCBQogcO = 0x6e1340;

//?isRetracting@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int Xq_Bdi_TjC = 0x12610b0;

//?isExpanded@PistonBlockActor@@QEBA_NXZ;
constexpr unsigned int D_LHvgIEZR = 0x1260f80;

//?getFacingDir@PistonBlockActor@@QEAAAEBVBlockPos@@AEAVBlockSource@@@Z;
//constexpr unsigned int VxWHJXdyOl = 0x1260660;

//?_hasBlockAttached@PistonBlockActor@@AEAA_NAEBVBlockPos@@@Z;
constexpr unsigned int mzGZCnpVKr = 0x1259ec0;

//?getName@ItemStackBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ;
constexpr unsigned int bFRmLvs_hd = 0xc8c830;

//?sendPistonActionEvent@BlockEventCoordinator@@QEAA?AW4CoordinatorResult@@AEBUPistonActionEvent@@@Z;
constexpr unsigned int VekUuoPYdu = 0xc1e4e0;